// <auto-generated />
using AgenciaViagens.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenciaViagens.Migrations
{
    [DbContext(typeof(AgenciaViagensDBContex))]
    [Migration("20240108170514_SecondDB")]
    partial class SecondDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgenciaViagens.Models.DestinoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("destino_name");

                    b.Property<string>("Preco")
                        .HasColumnType("longtext")
                        .HasColumnName("destino_preco");

                    b.HasKey("Id");

                    b.ToTable("destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Natal",
                            Preco = "800"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rio de Janeiro",
                            Preco = "1800"
                        },
                        new
                        {
                            Id = 3,
                            Name = "João Pessoa",
                            Preco = "600"
                        },
                        new
                        {
                            Id = 4,
                            Name = "São Paulo",
                            Preco = "2500"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
